### ISSUE TITLE
疑问：著作权

### ISSUE THREAD

**Issue by cloudwindy** [BeautyYuYanli/full-mark-composition-generator#29]
引用：https://zhuanlan.zhihu.com/p/54996890

**Comment by BeautyYuYanli** [comment]
目前还没有过关于高考作文的司法判例或解释, 本生成器又是原作文的二次演绎产物, 谈论著作权的话恐怕很难界定...

**Comment by cloudwindy** [comment]
哦，好吧，明白你的意思
