### ISSUE TITLE
關於複製的一些修改意見

### ISSUE THREAD

**Issue by Cluckbird** [BeautyYuYanli/full-mark-composition-generator#3]
詳見附件
[修改意見.txt](https://github.com/BeautyYuYanli/full-mark-composition-generator/files/5033357/default.txt)

**Comment by Cluckbird** [comment]
這樣應該都能兼容吧

**Comment by BeautyYuYanli** [comment]
我试过这个方案，在我自己的设备上还是不行。倒是现在使用的方案可以了
