### ISSUE TITLE
“音乐学”（来自音乐硕士的供稿）

### ISSUE THREAD

**Issue by rcswex** [BeautyYuYanli/full-mark-composition-generator#30]
主要学科：音乐学

两个相关联的学科：作曲技术理论 美学

生活在（）上：琴

名人 - 名言：
欣德米特 - 音乐是无意义的噪音，除非它触动了接受的心灵。
圣伊多禄 - 现在的音乐终将消逝，留下的只有将来的记忆。
叔本华 - 音乐，是任何地方都可以理解的真正的普遍性语言。
狄德罗 - 好的音乐是非常接近原始语言的。
贝多芬 - 若是为了更美丽的东西的话，任何规则都可以破坏。
卡拉扬 - 我可容忍一个错误的音符，绝不能容忍节奏有一点儿谬误。
萧伯纳 - 所有伟大的艺术和文学都是宣传。
江文也 - 如果我贫乏的本能不能对那音乐有任何感觉，就算知道它们的历史和理论又能如何呢？
何训田 - 每个人都有自己的香型。

3种思想（主义）：传统 后现代 超现代

3个性质：流传变异 即兴 审美错位

6个专业概念或术语：审美 新音乐学（New Musicology） 社会介入 民族志 乐谱文本 人工智能（AI）

以上是来自音乐硕士 知乎 @Raymond 的供稿。

**Comment by BeautyYuYanli** [comment]
已添加

**Comment by rcswex** [comment]
> 已添加

谢谢！在知乎做了宣传哦 https://zhuanlan.zhihu.com/p/183645344/ ，祝越来越好！
